# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Push to VPS

on:
  push:
    branches: [ master ]

jobs:
  push:

    runs-on: ubuntu-latest
    
    steps:
      - name: push
        env:
          PTERODACTYL_TOKEN: ${{ secrets.PTERODACTYL_TOKEN }}
        run: 'curl "https://pterodactyl.app/api/client/servers/<id>/power" -H "Authorization: Bearer $PTERODACTYL_TOKEN" -H "Content-Type: application/json" -X POST -d '{ "signal": "restart" }'
'
